// <auto-generated />
using System;
using APIPruebas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIPruebas.Migrations
{
    [DbContext(typeof(ContextoDb))]
    [Migration("20191022190352_AgregaTablaContactos")]
    partial class AgregaTablaContactos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIPruebas.Entidades.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasMaxLength(30);

                    b.Property<string>("Correo")
                        .HasMaxLength(30);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(30);

                    b.Property<string>("Puesto")
                        .HasMaxLength(30);

                    b.Property<string>("Telefono1")
                        .HasMaxLength(30);

                    b.Property<string>("Telefono2")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("APIPruebas.Entidades.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("Numero");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
